version: "3.8"

services:
  #frontend:
  #  restart: always
  #  build:
  #      context: ./Recharge-App/cougar-connect/
  #      dockerfile: Dockerfile
  #  container_name: frontend
  #  ports:
  #    - 19000:19000
  #    - 19001:19000
  #    - 19002:19000
  #    - 19006:19006
  #  volumes:
  #    - ./Recharge-App/cougar-connect/src:/opt/react_native_app/src
  backend:
    restart: always
    build:
        context: ./Recharge-Backend/
        dockerfile: Dockerfile
    container_name: backend
    ports:
      - 8080:8080
        #volumes:
        #  - ./Recharge-Backend/src/:/usr/actix/src
